tasks:
  - before: npm install -g @vue/cli && cd vue-typescript-class-lazyloading-mocha-webpack-gitpod-ts && npm install
    init: npm run serve
    command: vue ui
ports:
  - port: 8000
  - port: 8080